AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'dev/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.2

Style/Encoding:
  EnforcedStyle: when_needed

Style/StringLiterals:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/Documentation:
  Enabled: false
